# === Nombre de la aplicacion ===
spring.application.name=colegio-aem

# === Puerto dinamico ===
# En Railway se usa la variable PORT. En local se usa 8080
server.port=${PORT:8080}

# === Conexion a Base de Datos ===
# En local se usa la URL de XAMPP. En Railway, las variables las inyecta el sistema
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/colegio_aem?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aem_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aem1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === Configuracion JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# === Thymeleaf ===
spring.thymeleaf.cache=false

# === DevTools ===
spring.devtools.restart.enabled=true